package server.socket.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum SocketResponseType {
    PLAYER_APPEARANCE("PLAYER_APPEARANCE"),
    REMOVE_PLAYERS("REMOVE_PLAYERS"),
    PLAYER_MOTION_UPDATE("PLAYER_MOTION_UPDATE"),
    MOB_MOTION_UPDATE("MOB_MOTION_UPDATE"),
    REMOVE_MOBS("REMOVE_MOBS"),
    ADD_ITEMS_TO_MAP("ADD_ITEMS_TO_MAP"),
    REMOVE_ITEMS_FROM_MAP("REMOVE_ITEMS_FROM_MAP"),
    INVENTORY_UPDATE("INVENTORY_UPDATE"),
    ADD_EQUIP_ITEM("ADD_EQUIP_ITEM"),
    REMOVE_EQUIP_ITEM("REMOVE_EQUIP_ITEM"),
    INVENTORY_ERROR("INVENTORY_ERROR"),
    STATS_UPDATE("STATS_UPDATE"),
    UPDATE_DERIVED_ATTRIBUTES("UPDATE_DERIVED_ATTRIBUTES");

    public final String type;
}
